title: "AWSã§å§‹ã‚ã‚‹HCP Terraformå…¥é–€"
summary: "ğŸ“š ã“ã®Zenn Bookã«ã¤ã„ã¦
  HCP Terraformã«ã¯ã€çµ„ç¹”ã§Terraformã‚’é‹ç”¨ã™ã‚‹éš›ã«ä¾¿åˆ©ãªæ©Ÿèƒ½ãŒæ§˜ã€…ã‚ã‚Šã¾ã™ã€‚Terraformã¯çŸ¥ã£ã¦ã„ã‚‹ã‘ã©ã€HCP Terraformã¯çŸ¥ã‚‰ãªã„äººå‘ã‘ã«AWSã‚’ä½¿ã£ã¦HCP Terraformã®å„ç¨®æ©Ÿèƒ½ã‚’èª¬æ˜ã—ã¾ã™ã€‚
  ğŸ—“ï¸ æ›´æ–°å±¥æ­´
  ãƒ»2024/07/25: Terraform Cloud -> HCP Terraformã«æ›´æ–°
  ãƒ»2025/01/04: HCP Terraformé–¢é€£ã®ã‚¹ã‚¯ãƒªãƒ¼ãƒ³ã‚·ãƒ§ãƒƒãƒˆã‚’æœ€æ–°åŒ–ãƒ»Terraform Version 1.10ã«ã‚¢ãƒƒãƒ—ãƒ‡ãƒ¼ãƒˆ
  ãƒ»2025/01/05: tfe providerã‚’ä½¿ã£ãŸãƒãƒ³ã‚ºã‚ªãƒ³æ‰‹é †ã®è¿½åŠ 
  "
topics: ["aws", "terraform"]
published: true
price: 0 # æœ‰æ–™ã®å ´åˆ200ã€œ5000
# æœ¬ã«å«ã‚ã‚‹ãƒãƒ£ãƒ—ã‚¿ãƒ¼ã‚’é †ç•ªã«ä¸¦ã¹ã¾ã—ã‚‡ã†
chapters:
  - 01_introduction
  - 02_about_tfc
  - 03_tfc_concept
  - 04_tfc_create_org_user
  - 05_00_tfc_aws_deploy
  - 05_01_tfc_aws_archi
  - 05_02_aws_iam_role_create
  - 05_03_prepare_tf_file
  - 05_04_tfc_github_deploy
  - 05_05_tfe_tfc_github_deploy
  - 06_00_tfc_function
  - 06_01_workspace_explorer
  - 06_02_cost_estimation
  - 06_03_drift_detection
  - 06_04_continuous_validation
  - 06_05_ephemeral_workspaces
  - 06_06_private_registry
  - 06_07_no_code_provisioning
  - 06_08_policy_as_code
  - 06_09_run_task
  - 07_conclusion
